services:  
  fastapi_app: 
    image: jbadeyi/repo1:fastapi_app
    container_name: time-app
    # command: python main.py
    restart: unless-stopped
    tty: true
    ports:
      - "5000:5000"  
    networks:
      - mynetwork  

  nginx:  
    image: nginx:latest  
    container_name: nginx_base
    restart: unless-stopped
    tty: true
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf 
      - /etc/letsencrypt:/etc/letsencrypt  
      # - ./certbot/conf:/etc/letsencrypt  
    ports:
      - "80:80"   
      - "443:443" 
    networks:
      - mynetwork 

  certbot:  
    image: certbot/certbot  
    command: certonly --webroot --webroot-path=/var/www/certbot -d jbadeyi.xyz -d www.jbadeyi.xyz --email jbadeyi@icloud.com --agree-tos --non-interactive --quiet
    volumes:
      - ./certbot/www:/var/www/certbot 
      - ./certbot/conf:/etc/letsencrypt  
      - /etc/letsencrypt:/etc/letsencrypt 
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"  # Run Certbot renewal in a loop

networks:  
  mynetwork:  
