services:  
  app: 
    build: 
      context: . 
      dockerfile: Dockerfile
    container_name: app
    command: python main.py
    restart: unless-stopped
    tty: true
    volumes:
     - ./app:/app
    ports:
      - "5000:5000"  
    networks:
      - mynetwork  

  nginx:  
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: nginx
    restart: unless-stopped
    tty: true
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf 
      - /etc/letsencrypt:/etc/letsencrypt  
    ports:
      - "80:80"   
      - "443:443" 
    networks:
      - mynetwork 

  certbot:  
    image: certbot/certbot  
    volumes:
      - ./nginx:/var/www/certbot 
      - /etc/letsencrypt:/etc/letsencrypt  
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'" 

networks:  
  mynetwork:
